/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2;

/**
 *
 * @author Lourdes
 */
public class Simulador extends javax.swing.JFrame {

    /**
     * Creates new form Simulador
     */
    public Simulador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_AgregarEvento = new javax.swing.JDialog();
        LUGAR_EVENTO = new javax.swing.JTextField();
        CIUDAD_EVENTO = new javax.swing.JTextField();
        BOTON_AGREGAR_EVENTO = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FECHA_EVENTO = new com.toedter.calendar.JDateChooser();
        CANT_PERSONAS_EVENTO = new javax.swing.JSpinner();
        jd_AgregarUsuario = new javax.swing.JDialog();
        tcont = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btIngresar = new javax.swing.JButton();
        tusuar = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        NOMBRE_SOLISTA1 = new javax.swing.JTextField();
        EDAD_SOLISTA1 = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jd_TipoArtista = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        REGISTRAR_SOLISTA = new javax.swing.JButton();
        REGISTRAR_BANDA = new javax.swing.JButton();
        jd_AgregarSolista = new javax.swing.JDialog();
        BOTON_AGREGAR_SOLISTA = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        USUARIO_SOLISTA = new javax.swing.JTextField();
        GENERO_SOLISTA = new javax.swing.JTextField();
        NOMBRE_SOLISTA = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        CONTRASEÑA_SOLISTA = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        LISTA_CANCIONES_SOLISTA = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        CANCION_SOLISTA = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        EDAD_SOLISTA = new javax.swing.JSpinner();
        DURACION_SOLISTA = new javax.swing.JSpinner();
        jd_AgregarBanda = new javax.swing.JDialog();
        BOTON_AGREGAR_BANDA = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        USUARIO_BANDA = new javax.swing.JTextField();
        NOMBRE_BANDA = new javax.swing.JTextField();
        GENERO_BANDA = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        CONTRASEÑA_BANDA = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        LISTA_CANCIONES_BANDA = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        CANCION_BANDA = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        NUM_INTEGRANTES_BANDA = new javax.swing.JSpinner();
        DURACION_BANDA = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        REGISTRAR_ARTISTA = new javax.swing.JButton();
        REGISTRAR_EVENTO = new javax.swing.JButton();
        REGISTRAR_USUARIO = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();

        BOTON_AGREGAR_EVENTO.setText("Agregar");
        BOTON_AGREGAR_EVENTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTON_AGREGAR_EVENTOMouseClicked(evt);
            }
        });

        jLabel7.setText("Fecha:");

        jLabel8.setText("Lugar:");

        jLabel9.setText("Ciudad:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("Agregar Evento");

        jLabel11.setText("Cant. Personas:");

        javax.swing.GroupLayout jd_AgregarEventoLayout = new javax.swing.GroupLayout(jd_AgregarEvento.getContentPane());
        jd_AgregarEvento.getContentPane().setLayout(jd_AgregarEventoLayout);
        jd_AgregarEventoLayout.setHorizontalGroup(
            jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarEventoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_AgregarEventoLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(FECHA_EVENTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_AgregarEventoLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(CANT_PERSONAS_EVENTO))
                        .addGroup(jd_AgregarEventoLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(LUGAR_EVENTO))
                        .addGroup(jd_AgregarEventoLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(CIUDAD_EVENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarEventoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BOTON_AGREGAR_EVENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jd_AgregarEventoLayout.setVerticalGroup(
            jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(42, 42, 42)
                .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(FECHA_EVENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LUGAR_EVENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CIUDAD_EVENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jd_AgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CANT_PERSONAS_EVENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(BOTON_AGREGAR_EVENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel12.setText("Agregar Usuario");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Usuario:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Contraseña:");

        btIngresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btIngresar.setText("Agregar");
        btIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIngresarMouseClicked(evt);
            }
        });
        btIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActionPerformed(evt);
            }
        });
        btIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btIngresarKeyPressed(evt);
            }
        });

        tusuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tusuarMouseClicked(evt);
            }
        });
        tusuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tusuarActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Nombre:");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Edad:");

        jList1.setBackground(new java.awt.Color(0, 102, 102));
        jList1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(jList1);

        jList2.setBackground(new java.awt.Color(0, 102, 102));
        jList2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jList2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(jList2);

        jList3.setBackground(new java.awt.Color(0, 102, 102));
        jList3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jList3.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(jList3);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("AGREGAR");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("AGREGAR");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("AGREGAR");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CANCIONES");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ARTISTAS");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("EVENTOS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("SELECCIONE & AGREGUE");

        javax.swing.GroupLayout jd_AgregarUsuarioLayout = new javax.swing.GroupLayout(jd_AgregarUsuario.getContentPane());
        jd_AgregarUsuario.getContentPane().setLayout(jd_AgregarUsuarioLayout);
        jd_AgregarUsuarioLayout.setHorizontalGroup(
            jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarUsuarioLayout.createSequentialGroup()
                .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarUsuarioLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_AgregarUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(NOMBRE_SOLISTA1))
                            .addGroup(jd_AgregarUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(18, 18, 18)
                                .addComponent(EDAD_SOLISTA1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_AgregarUsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(tcont, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarUsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(tusuar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jd_AgregarUsuarioLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarUsuarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(57, 57, 57))
            .addGroup(jd_AgregarUsuarioLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel12)
                .addGap(87, 87, 87)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_AgregarUsuarioLayout.setVerticalGroup(
            jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarUsuarioLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarUsuarioLayout.createSequentialGroup()
                        .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(jd_AgregarUsuarioLayout.createSequentialGroup()
                        .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tusuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(NOMBRE_SOLISTA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_AgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(EDAD_SOLISTA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(btIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("SELECCIONE");

        REGISTRAR_SOLISTA.setBackground(new java.awt.Color(153, 0, 0));
        REGISTRAR_SOLISTA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        REGISTRAR_SOLISTA.setForeground(new java.awt.Color(255, 255, 255));
        REGISTRAR_SOLISTA.setText("Registrar Solista");
        REGISTRAR_SOLISTA.setBorderPainted(false);
        REGISTRAR_SOLISTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REGISTRAR_SOLISTAMouseClicked(evt);
            }
        });
        REGISTRAR_SOLISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRAR_SOLISTAActionPerformed(evt);
            }
        });

        REGISTRAR_BANDA.setBackground(new java.awt.Color(153, 0, 0));
        REGISTRAR_BANDA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        REGISTRAR_BANDA.setForeground(new java.awt.Color(255, 255, 255));
        REGISTRAR_BANDA.setText("Registrar Banda");
        REGISTRAR_BANDA.setBorderPainted(false);
        REGISTRAR_BANDA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REGISTRAR_BANDAMouseClicked(evt);
            }
        });
        REGISTRAR_BANDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRAR_BANDAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_TipoArtistaLayout = new javax.swing.GroupLayout(jd_TipoArtista.getContentPane());
        jd_TipoArtista.getContentPane().setLayout(jd_TipoArtistaLayout);
        jd_TipoArtistaLayout.setHorizontalGroup(
            jd_TipoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_TipoArtistaLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jd_TipoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(REGISTRAR_BANDA, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REGISTRAR_SOLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jd_TipoArtistaLayout.setVerticalGroup(
            jd_TipoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_TipoArtistaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addComponent(REGISTRAR_SOLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(REGISTRAR_BANDA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        BOTON_AGREGAR_SOLISTA.setText("Agregar");
        BOTON_AGREGAR_SOLISTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTON_AGREGAR_SOLISTAMouseClicked(evt);
            }
        });
        BOTON_AGREGAR_SOLISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_AGREGAR_SOLISTAActionPerformed(evt);
            }
        });

        jLabel15.setText("Usuario:");

        jLabel16.setText("Contraseña:");

        jLabel17.setText("Edad:");

        jLabel18.setText("Genero Musical:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel19.setText("Agregar Solista");

        jLabel20.setText("Nombre:");

        LISTA_CANCIONES_SOLISTA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Cancion", "Duracion"
            }
        ));
        jScrollPane1.setViewportView(LISTA_CANCIONES_SOLISTA);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Lista de Canciones");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Agregue una Cancion");

        jLabel23.setText("Nombre:");

        jLabel24.setText("Duracion:");

        javax.swing.GroupLayout jd_AgregarSolistaLayout = new javax.swing.GroupLayout(jd_AgregarSolista.getContentPane());
        jd_AgregarSolista.getContentPane().setLayout(jd_AgregarSolistaLayout);
        jd_AgregarSolistaLayout.setHorizontalGroup(
            jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarSolistaLayout.createSequentialGroup()
                        .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(DURACION_SOLISTA))
                            .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(CANCION_SOLISTA)))
                        .addGap(108, 108, 108)
                        .addComponent(BOTON_AGREGAR_SOLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                        .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(USUARIO_SOLISTA))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarSolistaLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(CONTRASEÑA_SOLISTA))
                            .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GENERO_SOLISTA, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                            .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NOMBRE_SOLISTA)
                                    .addComponent(EDAD_SOLISTA))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarSolistaLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarSolistaLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(116, 116, 116))))))
            .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel22))
                    .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jd_AgregarSolistaLayout.setVerticalGroup(
            jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(USUARIO_SOLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)))
                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarSolistaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(CONTRASEÑA_SOLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(EDAD_SOLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(NOMBRE_SOLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarSolistaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GENERO_SOLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(28, 28, 28)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(CANCION_SOLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTON_AGREGAR_SOLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_AgregarSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(DURACION_SOLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        BOTON_AGREGAR_BANDA.setText("Agregar");
        BOTON_AGREGAR_BANDA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTON_AGREGAR_BANDAMouseClicked(evt);
            }
        });
        BOTON_AGREGAR_BANDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_AGREGAR_BANDAActionPerformed(evt);
            }
        });

        jLabel25.setText("Usuario:");

        jLabel26.setText("Contraseña:");

        jLabel27.setText("Nº  Integrantes:");

        jLabel28.setText("Genero Musical:");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel29.setText("Agregar Banda");

        jLabel30.setText("Nombre:");

        LISTA_CANCIONES_BANDA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Cancion", "Duracion"
            }
        ));
        jScrollPane2.setViewportView(LISTA_CANCIONES_BANDA);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Lista de Canciones");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Agregue una Cancion");

        jLabel33.setText("Nombre:");

        jLabel34.setText("Duracion:");

        javax.swing.GroupLayout jd_AgregarBandaLayout = new javax.swing.GroupLayout(jd_AgregarBanda.getContentPane());
        jd_AgregarBanda.getContentPane().setLayout(jd_AgregarBandaLayout);
        jd_AgregarBandaLayout.setHorizontalGroup(
            jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarBandaLayout.createSequentialGroup()
                        .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_AgregarBandaLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(18, 18, 18)
                                .addComponent(DURACION_BANDA))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_AgregarBandaLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addComponent(CANCION_BANDA, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BOTON_AGREGAR_BANDA, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                        .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(USUARIO_BANDA))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarBandaLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(CONTRASEÑA_BANDA))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarBandaLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(NOMBRE_BANDA, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(NUM_INTEGRANTES_BANDA))
                            .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(GENERO_BANDA)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarBandaLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarBandaLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(116, 116, 116))))))
            .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel32)
                .addContainerGap(350, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarBandaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        jd_AgregarBandaLayout.setVerticalGroup(
            jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(USUARIO_BANDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31)))
                .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_AgregarBandaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(CONTRASEÑA_BANDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NOMBRE_BANDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addGap(31, 31, 31)
                        .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(NUM_INTEGRANTES_BANDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(GENERO_BANDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(CANCION_BANDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTON_AGREGAR_BANDA, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_AgregarBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(DURACION_BANDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("SHOW DE TALENTOS");

        REGISTRAR_ARTISTA.setBackground(new java.awt.Color(0, 0, 102));
        REGISTRAR_ARTISTA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        REGISTRAR_ARTISTA.setForeground(new java.awt.Color(255, 255, 255));
        REGISTRAR_ARTISTA.setText("Registrar Artista");
        REGISTRAR_ARTISTA.setBorderPainted(false);
        REGISTRAR_ARTISTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REGISTRAR_ARTISTAMouseClicked(evt);
            }
        });
        REGISTRAR_ARTISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRAR_ARTISTAActionPerformed(evt);
            }
        });

        REGISTRAR_EVENTO.setBackground(new java.awt.Color(0, 0, 102));
        REGISTRAR_EVENTO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        REGISTRAR_EVENTO.setForeground(new java.awt.Color(255, 255, 255));
        REGISTRAR_EVENTO.setText("Registrar Evento");
        REGISTRAR_EVENTO.setBorderPainted(false);
        REGISTRAR_EVENTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REGISTRAR_EVENTOMouseClicked(evt);
            }
        });
        REGISTRAR_EVENTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRAR_EVENTOActionPerformed(evt);
            }
        });

        REGISTRAR_USUARIO.setBackground(new java.awt.Color(0, 0, 102));
        REGISTRAR_USUARIO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        REGISTRAR_USUARIO.setForeground(new java.awt.Color(255, 255, 255));
        REGISTRAR_USUARIO.setText("Registrar Usuario");
        REGISTRAR_USUARIO.setBorderPainted(false);
        REGISTRAR_USUARIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REGISTRAR_USUARIOMouseClicked(evt);
            }
        });
        REGISTRAR_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRAR_USUARIOActionPerformed(evt);
            }
        });

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText("ADMINISTRADOR");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setBorderPainted(false);
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(REGISTRAR_EVENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(REGISTRAR_ARTISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(REGISTRAR_USUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(192, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(REGISTRAR_ARTISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(REGISTRAR_EVENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(REGISTRAR_USUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void REGISTRAR_ARTISTAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGISTRAR_ARTISTAMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_REGISTRAR_ARTISTAMouseClicked

    private void REGISTRAR_ARTISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRAR_ARTISTAActionPerformed
        // TODO add your handling code here:

        jd_TipoArtista.pack();
        jd_TipoArtista.setLocationRelativeTo(this);
        jd_TipoArtista.setModal(true);
        jd_TipoArtista.setVisible(true);
    }//GEN-LAST:event_REGISTRAR_ARTISTAActionPerformed

    private void REGISTRAR_EVENTOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGISTRAR_EVENTOMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTRAR_EVENTOMouseClicked

    private void REGISTRAR_EVENTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRAR_EVENTOActionPerformed
        // TODO add your handling code here:
        jd_AgregarEvento.pack();
        jd_AgregarEvento.setLocationRelativeTo(this);
        jd_AgregarEvento.setModal(true);
        jd_AgregarEvento.setVisible(true);

    }//GEN-LAST:event_REGISTRAR_EVENTOActionPerformed

    private void REGISTRAR_USUARIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGISTRAR_USUARIOMouseClicked
        // TODO add your handling code here:
        jd_AgregarUsuario.pack();
        jd_AgregarUsuario.setLocationRelativeTo(this);
        jd_AgregarUsuario.setModal(true);
        jd_AgregarUsuario.setVisible(true);

    }//GEN-LAST:event_REGISTRAR_USUARIOMouseClicked

    private void REGISTRAR_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRAR_USUARIOActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_REGISTRAR_USUARIOActionPerformed

    private void BOTON_AGREGAR_EVENTOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTON_AGREGAR_EVENTOMouseClicked
        // TODO add your handling code here:
        String nombre, contrasena, nom_art;
        int edad;
        try {
            nombre = tnomcliente.getText();
            contrasena = LUGAR_EVENTO.getText();
            edad = Integer.parseInt(CIUDAD_EVENTO.getText());

            Cliente p = new Cliente(nombre, contrasena, edad);

            usuarios.add(p);

            JOptionPane.showMessageDialog(this,
                "Valores Ingresado Correctamente");
            tnomcliente.setText("");
            LUGAR_EVENTO.setText("");
            CIUDAD_EVENTO.setText("");

            jd_AgregarEvento.setVisible(false);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_BOTON_AGREGAR_EVENTOMouseClicked

    private void btIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIngresarMouseClicked
        // TODO add your handling code here:
        boolean bandera=false;
        for(Usuario temp : usuarios){
            if (temp.getUsername().equals(tusuar.getText())
                && temp.getPassword().equals(tcont.getText())
            ){

                bandera= true;
                break;
            }
        }

        if (bandera){
            tusuar.setText("");
            tcont.setText("");
            jButton1.setEnabled(false);
            verusuario.setEnabled(true);
            salirusuario.setEnabled(true);
            arbolcliente.setEnabled(true);
            arbolartista.setEnabled(true);

            jd_AgregarUsuario.setVisible(false);
            jd_Ingresar.setVisible(false);

        }else{
            JOptionPane.showMessageDialog(jd_Ingresar, "Usuario Equivocado");
        }
    }//GEN-LAST:event_btIngresarMouseClicked

    private void btIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btIngresarActionPerformed

    private void btIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btIngresarKeyPressed

        if (tcont.getText().length()>=0){

            btIngresar.setEnabled(true);

        }else{

            btIngresar.setEnabled(false);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_btIngresarKeyPressed

    private void tusuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tusuarMouseClicked
        if(evt.getButton()==3){
            // jPopupMenu2.show(jd_Ingresar, evt.getX(), evt.getY());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tusuarMouseClicked

    private void tusuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tusuarActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_tusuarActionPerformed

    private void REGISTRAR_SOLISTAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGISTRAR_SOLISTAMouseClicked
        // TODO add your handling code here:
        jd_AgregarSolista.pack();
        jd_AgregarSolista.setLocationRelativeTo(this);
        jd_AgregarSolista.setModal(true);
        jd_AgregarSolista.setVisible(true);
    }//GEN-LAST:event_REGISTRAR_SOLISTAMouseClicked

    private void REGISTRAR_SOLISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRAR_SOLISTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTRAR_SOLISTAActionPerformed

    private void REGISTRAR_BANDAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGISTRAR_BANDAMouseClicked
        // TODO add your handling code here:
        jd_AgregarBanda.pack();
        jd_AgregarBanda.setLocationRelativeTo(this);
        jd_AgregarBanda.setModal(true);
        jd_AgregarBanda.setVisible(true);
    }//GEN-LAST:event_REGISTRAR_BANDAMouseClicked

    private void REGISTRAR_BANDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRAR_BANDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTRAR_BANDAActionPerformed

    private void BOTON_AGREGAR_SOLISTAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTON_AGREGAR_SOLISTAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTON_AGREGAR_SOLISTAMouseClicked

    private void BOTON_AGREGAR_SOLISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_AGREGAR_SOLISTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTON_AGREGAR_SOLISTAActionPerformed

    private void BOTON_AGREGAR_BANDAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTON_AGREGAR_BANDAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTON_AGREGAR_BANDAMouseClicked

    private void BOTON_AGREGAR_BANDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_AGREGAR_BANDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTON_AGREGAR_BANDAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTON_AGREGAR_BANDA;
    private javax.swing.JButton BOTON_AGREGAR_EVENTO;
    private javax.swing.JButton BOTON_AGREGAR_SOLISTA;
    private javax.swing.JTextField CANCION_BANDA;
    private javax.swing.JTextField CANCION_SOLISTA;
    private javax.swing.JSpinner CANT_PERSONAS_EVENTO;
    private javax.swing.JTextField CIUDAD_EVENTO;
    private javax.swing.JTextField CONTRASEÑA_BANDA;
    private javax.swing.JTextField CONTRASEÑA_SOLISTA;
    private javax.swing.JSpinner DURACION_BANDA;
    private javax.swing.JSpinner DURACION_SOLISTA;
    private javax.swing.JSpinner EDAD_SOLISTA;
    private javax.swing.JSpinner EDAD_SOLISTA1;
    private com.toedter.calendar.JDateChooser FECHA_EVENTO;
    private javax.swing.JTextField GENERO_BANDA;
    private javax.swing.JTextField GENERO_SOLISTA;
    private javax.swing.JTable LISTA_CANCIONES_BANDA;
    private javax.swing.JTable LISTA_CANCIONES_SOLISTA;
    private javax.swing.JTextField LUGAR_EVENTO;
    private javax.swing.JTextField NOMBRE_BANDA;
    private javax.swing.JTextField NOMBRE_SOLISTA;
    private javax.swing.JTextField NOMBRE_SOLISTA1;
    private javax.swing.JSpinner NUM_INTEGRANTES_BANDA;
    private javax.swing.JButton REGISTRAR_ARTISTA;
    private javax.swing.JButton REGISTRAR_BANDA;
    private javax.swing.JButton REGISTRAR_EVENTO;
    private javax.swing.JButton REGISTRAR_SOLISTA;
    private javax.swing.JButton REGISTRAR_USUARIO;
    private javax.swing.JTextField USUARIO_BANDA;
    private javax.swing.JTextField USUARIO_SOLISTA;
    private javax.swing.JButton btIngresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog jd_AgregarBanda;
    private javax.swing.JDialog jd_AgregarEvento;
    private javax.swing.JDialog jd_AgregarSolista;
    private javax.swing.JDialog jd_AgregarUsuario;
    private javax.swing.JDialog jd_TipoArtista;
    private javax.swing.JTextField tcont;
    private javax.swing.JTextField tusuar;
    // End of variables declaration//GEN-END:variables
}
